package.json: depend on 'coffee-script' to fix builds
Otherwise it fails on Circle with:

```
Error: Cannot find module 'coffee-script/register'
```

It passes locally for me and I could see the
`node_modules/coffee-script` directory. However on Circle this
dependency is missing (not sure why).